### PR TITLE
chores(dockerfiles): New lightweight and improved docker images 

### PR DESCRIPTION
**Pull request by bs-matil**
We would like to seperate the thrift backend from anything else which has following advantages:

- Boot time optimization:
   -   Thrift backend needs only seconds to boot
- Memory consumptions:
  -   The Thrift backend needs only   ~350 mb of ram while liferay needs > 1GB less
- Complex deployment scenarios:
  - multible frontend/backends are commbined.

### CODE REVIEW

**Comment by maxhbr** [comment]
The long term goal is to replace the old docker images, but until all features are contained in the new approach, they will be placed in `/docker-images-backend`.

### For testing one can follow the description in the `docker-images-backend/README.md`:
after building the "old" docker images and building the new docker images with
```
$ cd ./v2/docker-images-backend
$ docker-compose build
```
one can start a working deployment with: 
```
$ cd ./v2
$ ( cd /PATH/TO/SW360; mvn package -DskipTests )
$ find /PATH/TO/SW360/frontend -name '*.war' -exec cp -v {} ../_deploy \;
$ docker-compose -f docker-images-backend/docker-compose.yaml -f docker-images-frontend/docker-compose.yaml up
```
After that SW360 can be accessed on `https://localhost:8443`.

**Comment by bs-matil** [comment]
> `/docker-images-v2`.

actually it will be /docker-images-backend

**Comment by maxhbr** [comment]
> actually it will be /docker-images-backend

Oh, I missed the renaming. This PR should then add text to the top level `README.md`, and describe the situation and that there is currently redundancy.

**Comment by bs-matil** [comment]
~~can you do so?~~
alternatively we can also rename back to v2?

**Comment by kallesoranko** [comment]
I did some testing with this PR and deployed sw360-backend to our internal GKE cluster. Couple of points:

*  In `v2/docker-images-backend/backend/Dockerfile` specific commit or branch have to be checked out before building since the changes with Liferay 7. 

* What is the reason why rest is not deployed to backend container? Should there be an additional container for rest?

**Comment by maxhbr** [comment]
> * In `v2/docker-images-backend/backend/Dockerfile` specific commit or branch have to be checked out before building since the changes with Liferay 7.

But the container here only build the backend and exclude everything from Liferay. How does the LR7 migration result in problems?

> * What is the reason why rest is not deployed to backend container? Should there be an additional container for rest?

Yes, there are other containers for rest, which are not yet contributed and waiting for the merge of this PR. They are part of the frontend.

**Comment by oheger-bosch** [comment]
In the SW360 tech call we talked about this PR, and the conclusion was that it should be merged. Based on this, I would then try to update the chores project to the current state of SW360.

Any objections against merging?

**Comment by mcjaeger** [comment]
no ...

**Pull request merged**
