### PR TITLE
fix(proxy): couchdb-lucene/prepare proxy was incorrect

### PR DESCRIPTION
**Pull request by maxhbr**
This should solve #36.

### CODE REVIEW

**Comment by maxhbr** [comment]
This is currently untested.

**Comment by alexbrdn** [comment]
I couldn't get it to work with proxy. Also, the build without proxy didn't seem to work until I commented out this https://github.com/sw360/sw360chores/blob/master/deployment/docker-compose.yml#L37 and this https://github.com/sw360/sw360chores/blob/master/deployment/docker-compose.yml#L88 options

**Comment by maxhbr** [comment]
That is confusing. This PR changes something in the `--prepare` step, which does not use the file `docker-compose.yml`. Especially the changes at https://github.com/sw360/sw360chores/pull/37/files#diff-37e1c69ef3a9e5aac0d8e17944e8c754R42 should be self-contained and not affected by your change.

**Comment by maxhbr** [comment]
superfluous due to #48

**Pull request closed without merging**
