### PR TITLE
Updated to be compatible with SW360 version 12

### PR DESCRIPTION
**Pull request by andreaslarfors**
This is the bare-minimum changes needed to make sw360chores work with new SW360.
Includes:
- update to openjdk11
- move from alpine images to slim
- couchdb update to 2.1
- adding default couchdb local.ini file (no longer exists by default)
- adding single_node mode to couchdb (required since addition of cluster mode in 2.0)
- creating couchdb system tables with sw360empty container 
- upgrade to Liferay 7.3.3-GA4
- updating garbage collectors to recommended one for openjdk11

### CODE REVIEW

**Comment by mcjaeger** [comment]
Hi thanks for your contribution, but is it maybe conflicting with this PR?

https://github.com/sw360/sw360chores/pull/81

**Comment by mcjaeger** [comment]
thinking about it, technically maybe not, since the entire stuff from Oliver was going to the "v2" dir ...

**Comment by andreaslarfors** [comment]
> thinking about it, technically maybe not, since the entire stuff from Oliver was going to the "v2" dir ...

Yes, I also did some work on v2 but couldn't make it work... 
So I did not include any changes to the v2 directory.

Looking closer at #81 I can see that the only non-v2 changes were to:
.gitignore
configuration/COUCHDB_PASSWORD
configuration/COUCHDB_USER

As I did not change these three files there are technically no conflicts.

Whether the work in #81 depends on any changes made in this PR is a different question, but it looks quite separate.

**Comment by andreaslarfors** [comment]
@mcjaeger this has now been updated with all changes discussed in Slack. Tests are now passing too.
Let me know if you have any questions about the merge.

**Comment by mcjaeger** [comment]
testing seems to build nicely:

Screenshot 2021-01-11 at 23 19 43

(also on mac), but the deployment of sw360 cannot be brought to an end:

Screenshot 2021-01-11 at 23 25 06

So the issue is that among the prerequisites, the commons compress is missing:

https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.20/commons-compress-1.20.jar commons-compress-1.20.jar

(required because Apache POI was upgraded to four-something which requires this nowadays)

-> merging because this is not an issue of this branch here.

**Review by mcjaeger — APPROVED** [review]
changes look inline with what was there before

**Pull request merged**
